name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Spring Boot Build
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      # Docker Build (레포지토리 루트 기준)
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .

      # DockerHub Login
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # DockerHub Push
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test


  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image on EC2
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

      - name: Run New Container with Env
        run: |
          if [ $(sudo docker ps -a -q -f name=spring-cicd-test) ]; then
            sudo docker rm -f spring-cicd-test
          fi
          sudo docker run -d -p 8080:8080 --name spring-cicd-test \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
            -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }} \
            -e TOSS_BASE_URL=${{ secrets.TOSS_BASE_URL }} \
            -e EMAIL=${{ secrets.EMAIL }} \
            -e GOOGLE_PASSWORD=${{ secrets.GOOGLE_PASSWORD }} \
            -e BUCKET_NAME=${{ secrets.BUCKET_NAME}} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID}} \
            -e GOOGLE_OAUTH_KEY=${{ secrets.GOOGLE_OAUTH_KEY}} \
            -e BASE_URL=${{ secrets.BASE_URL}} \
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

      - name: Cleanup Old Images
        run: sudo docker system prune -f

#isFucked = true